# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Install node version
    - name: Setup Node.js environment
      uses: actions/setup-node@v1
      with:
        node-version: '12.6.0'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@jiaming0708'

    - run: yarn install
    - run: yarn test
    # - run: npm publish
    #   env:
    #     NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
